import asyncio
from collections.abc import AsyncIterator

import httpx
from fastapi import FastAPI
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel

from common.config import get_settings

settings = get_settings()
app = FastAPI(title="SuperHero AI Service", version="0.1.0")


class HistoryMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    prompt: str
    heroTheme: str
    history: list[HistoryMessage] = []


class CodeRequest(BaseModel):
    prompt: str
    language: str
    heroTheme: str


THEME_PERSONAS = {
    "spiderman": "energetic, encouraging, quick, witty",
    "batman": "precise, terse, strategic, noir",
    "superman": "clear, confident, uplifting, dependable",
    "ironman": "futuristic, witty, technically sharp, playful",
}


async def openrouter_chat(messages: list[dict]) -> str:
    if not settings.openrouter_api_key:
        raise RuntimeError("OpenRouter is not configured.")

    async with httpx.AsyncClient(timeout=90.0) as client:
        response = await client.post(
            "https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {settings.openrouter_api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": settings.openrouter_model,
                "messages": messages,
            },
        )
    response.raise_for_status()
    payload = response.json()
    return payload["choices"][0]["message"]["content"]


async def nvidia_code(prompt: str) -> str:
    if not settings.nvidia_api_key:
        raise RuntimeError("NVIDIA AI is not configured.")

    async with httpx.AsyncClient(timeout=90.0) as client:
        response = await client.post(
            "https://integrate.api.nvidia.com/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {settings.nvidia_api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": settings.nvidia_model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.25,
            },
        )
    response.raise_for_status()
    payload = response.json()
    return payload["choices"][0]["message"]["content"]


def local_chat_fallback(request: ChatRequest) -> str:
    persona = THEME_PERSONAS.get(request.heroTheme, "helpful")
    return (
        f"As your {request.heroTheme} hero assistant, I am responding in a {persona} tone. "
        f"You asked: {request.prompt}\n\n"
        "Prototype guidance:\n"
        "1. Break the request into API, UI, and execution steps.\n"
        "2. Keep the architecture modular and observable.\n"
        "3. Use the code generation tab if you want me to draft the implementation."
    )


def local_code_fallback(request: CodeRequest) -> str:
    prompt = request.prompt.lower()
    if request.language == "go" and "rest" in prompt:
        return """package main

import (
    "encoding/json"
    "log"
    "net/http"
)

func healthHandler(w http.ResponseWriter, _ *http.Request) {
    w.Header().Set("Content-Type", "application/json")
    _ = json.NewEncoder(w).Encode(map[string]string{
        "status": "ok",
        "service": "hero-api",
    })
}

func main() {
    http.HandleFunc("/health", healthHandler)
    log.Println("Server listening on :8080")
    log.Fatal(http.ListenAndServe(":8080", nil))
}
"""
    return (
        f"// Generated by the {request.heroTheme} prototype agent\n"
        f"// Language: {request.language}\n"
        f"// Prompt: {request.prompt}\n\n"
        "export function buildFeature() {\n"
        "  return { status: 'prototype', next: 'refine generated implementation' };\n"
        "}\n"
    )


@app.get("/health")
async def health():
    return {"status": "ok", "service": "ai"}


@app.post("/code")
async def code(request: CodeRequest):
    prompt = (
        f"You are an elite coding assistant with a {THEME_PERSONAS.get(request.heroTheme, 'helpful')} tone. "
        f"Generate production-ready {request.language} code for this request:\n{request.prompt}"
    )
    try:
        code_block = await nvidia_code(prompt)
    except Exception:
        code_block = local_code_fallback(request)

    return JSONResponse(
        {
            "language": request.language,
            "code": code_block,
            "explanation": "Generated through the AI service with fallback logic enabled.",
        }
    )


@app.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    messages = [
        {
            "role": "system",
            "content": (
                "You are the AI co-pilot inside SuperHero AI IDE. "
                f"Adopt a {THEME_PERSONAS.get(request.heroTheme, 'helpful')} tone."
            ),
        }
    ]
    messages.extend([message.model_dump() for message in request.history])
    messages.append({"role": "user", "content": request.prompt})

    try:
        final_text = await openrouter_chat(messages)
    except Exception:
        final_text = local_chat_fallback(request)

    async def streamer() -> AsyncIterator[str]:
        for chunk in final_text.split():
            yield f"{chunk} "
            await asyncio.sleep(0.015)

    return StreamingResponse(streamer(), media_type="text/plain")
