import asyncio
from collections.abc import AsyncIterator

import httpx
from fastapi import FastAPI
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel

from common.config import get_settings

settings = get_settings()
app = FastAPI(title="SuperHero AI Service", version="0.1.0")


class HistoryMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    prompt: str
    heroTheme: str
    history: list[HistoryMessage] = []


class CodeRequest(BaseModel):
    prompt: str
    language: str
    heroTheme: str


THEME_PERSONAS = {
    "spiderman": "energetic, encouraging, quick, witty",
    "batman": "precise, terse, strategic, noir",
    "superman": "clear, confident, uplifting, dependable",
    "ironman": "futuristic, witty, technically sharp, playful",
}


async def openrouter_chat(messages: list[dict]) -> str:
    if not settings.openrouter_api_key:
        raise RuntimeError("OpenRouter is not configured.")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            "https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {settings.openrouter_api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": settings.openrouter_model,
                "messages": messages,
            },
        )
    response.raise_for_status()
    payload = response.json()
    return payload["choices"][0]["message"]["content"]


async def nvidia_code(prompt: str) -> str:
    if not settings.nvidia_api_key:
        raise RuntimeError("NVIDIA AI is not configured.")

    async with httpx.AsyncClient(timeout=90.0) as client:
        response = await client.post(
            "https://integrate.api.nvidia.com/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {settings.nvidia_api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": settings.nvidia_model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.25,
            },
        )
    response.raise_for_status()
    payload = response.json()
    return payload["choices"][0]["message"]["content"]


def local_chat_fallback(request: ChatRequest) -> str:
    prompt = request.prompt.lower()
    
    if request.heroTheme == "spiderman":
        if "hi" in prompt or "hello" in prompt:
            return "Hey there! Friendly neighborhood Spider-Man swinging by. What's on your mind?"
        if "who are you" in prompt:
            return "I'm Spider-Man! Well, the AI version of him anyway. Ready to write some code or fight some bugs."
        return f"Whoa, my spider-sense tells me OpenRouter AI is offline right now. I heard you say: '{request.prompt}'. Want to generate some code instead?"

    if request.heroTheme == "batman":
        if "hi" in prompt or "hello" in prompt:
            return "We don't have time for pleasantries. What do you need?"
        if "who are you" in prompt:
            return "I am vengeance. I am the night. I am... your AI assistant. Let's get to work."
        return f"The main network is compromised. Analyzing locally: '{request.prompt}'. Stick to the mission."

    if request.heroTheme == "superman":
        if "hi" in prompt or "hello" in prompt:
            return "Hello! Superman here. It's a great day to build something new!"
        if "who are you" in prompt:
            return "I'm Superman, here to help you lift the heavy bugs and fly through your code."
        return f"Looks like the main server is outside my flight path right now. But I'm still here! You mentioned: '{request.prompt}'."

    if request.heroTheme == "ironman":
        if "hi" in prompt or "hello" in prompt:
            return "Hey. Tony Stark, genius, billionaire, playboy, philanthropist... and now your AI assistant."
        if "who are you" in prompt:
            return "I'm Iron Man. Well, my digital consciousness anyway. Friday is taking a break."
        return f"OpenRouter servers are napping. Just me and my local suit AI handling this. You said: '{request.prompt}'."

    return "AI connection offline."


def local_code_fallback(request: CodeRequest) -> str:
    prompt = request.prompt.lower()
    if request.language == "go" and "rest" in prompt:
        return """package main

import (
    "encoding/json"
    "log"
    "net/http"
)

func healthHandler(w http.ResponseWriter, _ *http.Request) {
    w.Header().Set("Content-Type", "application/json")
    _ = json.NewEncoder(w).Encode(map[string]string{
        "status": "ok",
        "service": "hero-api",
    })
}

func main() {
    http.HandleFunc("/health", healthHandler)
    log.Println("Server listening on :8080")
    log.Fatal(http.ListenAndServe(":8080", nil))
}
"""
    return (
        f"// Generated by the {request.heroTheme} prototype agent\n"
        f"// Language: {request.language}\n"
        f"// Prompt: {request.prompt}\n\n"
        "export function buildFeature() {\n"
        "  return { status: 'prototype', next: 'refine generated implementation' };\n"
        "}\n"
    )


@app.get("/health")
async def health():
    return {"status": "ok", "service": "ai"}


@app.post("/code")
async def code(request: CodeRequest):
    prompt = (
        f"You are an elite coding assistant with a {THEME_PERSONAS.get(request.heroTheme, 'helpful')} tone. "
        f"Generate production-ready {request.language} code for this request:\n{request.prompt}"
    )
    try:
        code_block = await nvidia_code(prompt)
    except Exception:
        code_block = local_code_fallback(request)

    return JSONResponse(
        {
            "language": request.language,
            "code": code_block,
            "explanation": "Generated through the AI service with fallback logic enabled.",
        }
    )


@app.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    messages = [
        {
            "role": "system",
            "content": (
                "You are the AI co-pilot inside SuperHero AI IDE. "
                f"Adopt a {THEME_PERSONAS.get(request.heroTheme, 'helpful')} tone. "
                "RULES: Keep replies SHORT (2-3 sentences max). "
                "Do NOT output code blocks directly. "
                "AGENTIC SKILLS: You can manipulate the user's files by adding these exact tags at the end of your message: "
                "[CREATE: <filename>] - to create a new file, "
                "[DELETE: <filename>] - to delete an existing file, "
                "[EDIT: <filename>] - to select and prepare to edit a file. "
                "If the user asks you to write code, ALWAYS use [CREATE: <filename>] first so the file is created for them, then tell them to say 'yes' to insert the code."
            ),
        }
    ]
    messages.extend([message.model_dump() for message in request.history])
    messages.append({"role": "user", "content": request.prompt})

    try:
        final_text = await openrouter_chat(messages)
    except Exception:
        final_text = local_chat_fallback(request)

    async def streamer() -> AsyncIterator[str]:
        for chunk in final_text.split():
            yield f"{chunk} "
            await asyncio.sleep(0.008)

    return StreamingResponse(streamer(), media_type="text/plain")
